### ISSUE TITLE
Post Keda  Manager build generate module template with old images

### ISSUE THREAD

**Issue by dbadura** [kyma-project/keda-manager#223]
In lines 67 and 76 there are old images.

**Comment by MichalKalke** [comment]
In last job `post-keda-module-build` (983f269fc0d2d22b1f23e705e3679ce926896fd5) the generated module template has such images:
- europe-docker.pkg.dev/kyma-project/prod/keda-manager:v20230621-a32a09b8
- europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda:2.10.1 

due to last tag bump (https://github.com/kyma-project/keda-manager/commit/a32a09b878b0837df14abb76598092d764dc0972) that is the reason of old images in module-template.

**Comment by dbadura** [comment]
After longer investigation, we got information that the image tag is taken from https://github.com/kyma-project/keda-manager/blob/main/sec-scanners-config.yaml.

**Comment by dbadura** [comment]
Bumping image in https://github.com/kyma-project/keda-manager/blob/main/sec-scanners-config.yaml makes the module template correct.
